import Link from "next/link";

export default function Home() {
  return <main className="shell">
    <nav className="nav"><Link className="logo" href="/">bli<span>t</span>le</Link><div className="nav-right"><span className="nav-status"><i /> Garmin-ready</span><Link className="nav-link" href="/pay">Get License <span aria-hidden="true">↗</span></Link></div></nav>
    <section className="hero">
      <div className="hero-copy"><div className="kicker">Premium Garmin application <span className="kicker-line" /></div><h1>Make every glance <em>count.</em></h1><p className="lede">A focused premium layer for your Garmin. Clean information, one calm tap, and a license that stays yours.</p><div className="hero-actions"><Link className="button accent" href="/pay">Get your license <span aria-hidden="true">↗</span></Link><span className="microcopy">One device · direct payment</span></div></div>
      <div className="hero-art" aria-label="Blitle running on a Garmin watch"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="device"><div className="device-speaker" /><div className="device-screen"><div className="screen-top"><span>BLITLE</span><span>09:41</span></div><div className="screen-value">72<span>bpm</span></div><div className="screen-label">steady effort</div><div className="screen-chart"><i /><i /><i /><i /><i /><i /><i /><i /></div><div className="screen-footer"><span>RUN</span><b>READY</b></div></div></div><div className="visual-tag tag-top">01 / focus</div><div className="visual-tag tag-bottom">live on your wrist</div></div>
    </section>
    <section className="signal-strip" aria-label="Product highlights"><div><strong>01</strong><span>Direct ownership</span></div><div><strong>02</strong><span>One device activation</span></div><div><strong>03</strong><span>Built for real use</span></div></section>
    <section className="section"><div className="section-heading"><div><div className="kicker">The Blitle difference</div><h2>Quiet software.<br /><em>Useful signal.</em></h2></div><p>Everything important stays close: on your watch, in your rhythm, without another noisy dashboard to manage.</p></div><div className="grid"><article className="feature feature-dark"><span className="feature-number">01</span><h3>Pay direct</h3><p>Send the configured amount to a public address. No custodial checkout and no account maze.</p><span className="feature-arrow">↗</span></article><article className="feature feature-light"><span className="feature-number">02</span><h3>Keep it personal</h3><p>Your license activates once and binds to one Garmin installation. Simple by design.</p><span className="feature-arrow">↗</span></article><article className="feature feature-accent"><span className="feature-number">03</span><h3>Stay in flow</h3><p>Once activated, Blitle keeps your entitlement locally and rechecks when available.</p><span className="feature-arrow">↗</span></article></div></section>
    <footer className="footer"><Link className="logo" href="/">bli<span>t</span>le</Link><span>Premium, without the noise.</span><Link href="/pay">Start here <span aria-hidden="true">↗</span></Link></footer>
  </main>;
}
