import Link from "next/link";

export default function Home() {
  return <main className="trust-shell">
    <nav className="trust-nav"><Link className="logo" href="/">bli<span>t</span>le</Link><div className="trust-nav-links"><Link href="#how-it-works">How it works</Link><Link href="#details">Details</Link><Link className="trust-nav-cta" href="/pay">Get a license <span aria-hidden="true">↗</span></Link></div></nav>
    <section className="trust-hero"><div className="trust-hero-copy"><div className="trust-eyebrow"><span /> Premium Garmin software</div><h1>A clear way to add more to your <em>watch.</em></h1><p className="trust-lede">Blitle is a focused premium application for Garmin. Buy one license, activate one device, and keep your experience simple.</p><div className="trust-actions"><Link className="trust-button" href="/pay">View payment details <span aria-hidden="true">↗</span></Link><span className="trust-note">No account required</span></div></div><div className="trust-access-panel"><div className="access-panel-top"><span className="access-label">Your Blitle access</span><span className="access-status"><i /> Ready to start</span></div><div className="access-title">One license.<br /><em>One Garmin.</em></div><div className="access-list"><div><b>✓</b><span>Direct USDT payment</span></div><div><b>✓</b><span>Transaction verification</span></div><div><b>✓</b><span>License key delivery</span></div></div><div className="access-price"><span>Complete checkout</span><strong>2.34 <small>USDT</small></strong></div></div></section>
    <section className="trust-proof" id="details"><div className="proof-intro"><div className="trust-eyebrow">Designed to be understood</div><h2>Less noise.<br /><em>More confidence.</em></h2></div><div className="proof-copy"><p>There is no hidden subscription, account maze, or custodial checkout. You see the receiving address and amount before you send anything.</p><p>After the network confirms your payment, Blitle gives you a license key for your Garmin installation.</p></div></section>
    <section className="trust-process" id="how-it-works"><div className="process-heading"><div className="trust-eyebrow">How it works</div><h2>Three straightforward steps.</h2></div><div className="process-grid"><article><span>01</span><h3>Review</h3><p>See the exact amount, network, and public receiving address before you pay.</p></article><article><span>02</span><h3>Send</h3><p>Transfer USDT directly on Ethereum mainnet from your own wallet.</p></article><article><span>03</span><h3>Activate</h3><p>Submit the transaction hash and receive a key for one Garmin device.</p></article></div></section>
    <section className="trust-cta"><div><div className="trust-eyebrow">Ready when you are</div><h2>Start with the facts.</h2></div><Link className="trust-button trust-button-light" href="/pay">Open secure checkout <span aria-hidden="true">↗</span></Link></section>
    <footer className="trust-footer"><Link className="logo" href="/">bli<span>t</span>le</Link><span>Premium Garmin software with transparent payment.</span><Link href="/pay">Payment details <span aria-hidden="true">↗</span></Link></footer>
  </main>;
}
